import Testing

@testable import AdventOfCode

struct Day08Tests {
    let testPart1Result1 = 2
    let testPart1Data1 = """
    ..........
    ..........
    ..........
    ....a.....
    ..........
    .....a....
    ..........
    ..........
    ..........
    ..........

    """
    let testPart1Result2 = 4
    let testPart1Data2 = """
    ..........
    ..........
    ..........
    ....a.....
    ........a.
    .....a....
    ..........
    ..........
    ..........
    ..........

    """
    let testPart1Result3 = 4
    let testPart1Data3 = """
    ..........
    ..........
    ..........
    ....a.....
    ........a.
    .....a....
    ..........
    ......A...
    ..........
    ..........

    """
    let testPart1Result = 14
    let testPart2Result = 34
    let testData = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............

    """

    let testPart2Result1 = 9
    let testPart2Data1 = """
    T.........
    ...T......
    .T........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........

    """

    @Test func testPart1Input1() async throws {
        let challenge = Day08(data: testPart1Data1)
        #expect(challenge.part1() == testPart1Result1)
    }

    @Test func testPart1Input2() async throws {
        let challenge = Day08(data: testPart1Data2)
        #expect(challenge.part1() == testPart1Result2)
    }

    @Test func testPart1Input3() async throws {
        let challenge = Day08(data: testPart1Data3)
        #expect(challenge.part1() == testPart1Result3)
    }

    @Test func testPart1Input4() async throws {
        let challenge = Day08(data: testData)
        #expect(challenge.part1() == testPart1Result)
    }

    @Test func testPart2Input1() async throws {
        let challenge = Day08(data: testPart2Data1)
        #expect(challenge.part2() == testPart2Result1)
    }

    @Test func testPart2Input2() async throws {
        let challenge = Day08(data: testData)
        #expect(challenge.part2() == testPart2Result)
    }
}
